version: 2

sphinx:
  configuration: docs/source/conf.py

build:
  os: "ubuntu-24.04"
  tools:
    python: "3.14"
  jobs:
    post_create_environment:
      - python -m pip install poetry
    post_install:
      - VIRTUAL_ENV=$READTHEDOCS_VIRTUALENV_PATH poetry install
