version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.12"
  jobs:
    post_install:
      - pip install -U poetry
      - poetry config virtualenvs.create false
      - poetry install -E docs
